### ISSUE TITLE
tiktok videos download problem. Code no more working 

### ISSUE THREAD

**Issue by munazza3242** [Karim-Arab/Tiktok2Youtube-shorts#11]
Hi Karim-Arab
 I am using this from previous some weeks but now this is not working, i try it on multiple pc but not work. This was so amazing I humble request to you please check it and look what's problem with that and fix it. Thank You

**Comment by Karim-Arab** [comment]
i updated the script replace it with one u have and use syntax  like this 

node allvideosuser https://www.tiktok.com/@davidbeckham

**Comment by munazza3242** [comment]
Thank you so much [Karim-Arab] **Now, it's working perfectly**
