### ISSUE TITLE
youtube upload

### ISSUE THREAD

**Issue by iGetAlways** [Karim-Arab/Tiktok2Youtube-shorts#6]
is it only downloading tiktok videos or there is a youtube upload code?

**Comment by Karim-Arab** [comment]
yea just download tiktoks non-watermark allvideosuser.js is working for downloading all user videos non-watermark
youtube doesn't need code it just drags and drops it will upload them all

**Comment by Karim-Arab** [comment]
incase you want to bypass youtube 50's daily limit upload check that repo https://github.com/Reamasa/Stekeblads-Video-Uploader

**Comment by Karim-Arab** [comment]
incase you want to bypass youtube 50's daily limit uploads,  check that repo https://github.com/Stekeblad/Stekeblads-Video-Uploader
