### ISSUE TITLE
Greate work but im not seeing the downloaded videos

### ISSUE THREAD

**Issue by bloodymoney** [Karim-Arab/Tiktok2Youtube-shorts#7]
hello karim , this is a nice project , but im having trouble when using both methods it runs but  where are the downloaded videos?

**Comment by Karim-Arab** [comment]
currently allvideosuser.js is working the videos saved in project location in folder by same name of user
tiktok.js  outdated need updated to bypass bot detections

**Comment by bloodymoney** [comment]
yeah i tested it out with a firend , allvideosuser.js worked for him , idk  . anyway fantastic work
