### ISSUE TITLE
Can't pass video description as mp4 title 

### ISSUE THREAD

**Issue by i6c** [Karim-Arab/Tiktok2Youtube-shorts#9]
Hi. So I defined the video des variable before the save function  but it doesn't save with the video description  as the name . Can you help me with this , the var for saving I put is (path+videoDes+'.mp4');  but it only saves as '.mp4' with no title.

**Comment by dori921** [comment]
Hey @i6c . Did u solve it ?

**Comment by Karim-Arab** [comment]
guys description not in profile page it must enter every video to get it unlike search results

**Comment by Karim-Arab** [comment]
i just notice that tiktok added description now in profile nice, now it will be saved in names.txt


uses new syntax
node allvideosuser url profile link

**Comment by i6c** [comment]
@Karim-Arab ok,  this is tedious on having to manually upload this videos because it is saved in names.txt , i have to manually upload this all  and go copy paste from names.txt

**Comment by Karim-Arab** [comment]
i can't make it fully automated because youtube must have api key and has limations, you can use zapier or alternatives to automate this task https://prnt.sc/9qcfCfL4j26W

the point of script not only reuse for shorts but also insta&facebook reels and snapchat spotlight

**Comment by dori921** [comment]
You don't have to use API for upload, here is a [script ](https://github.com/fawazahmed0/youtube-uploader)you can implement on your script. I've tried to do by myself but i don't have the right knowledge.

**Comment by i6c** [comment]
@Karim-Arab I don't know much of js, mainly Python bro. But maybe we can make read names.txt each line and rename each video file accordingly . And use selenium if there really is no other way

**Comment by Karim-Arab** [comment]
@i6c  it's tricky i had to strip illegal characters of windows file naming but here you go


`const { url } = require("inspector");
const { abort, nextTick } = require("process");
const puppeteer = require("puppeteer-extra");
const { PassThrough } = require("stream");
const stealthPlugin = require("puppeteer-extra-plugin-stealth")();

["chrome.runtime", "navigator.languages"].forEach(a =>
  stealthPlugin.enabledEvasions.delete(a)
);

puppeteer.use(stealthPlugin);

main();
async function main() {
  const browser = await puppeteer.launch( { headless: true } );
  const page = await browser.newPage();

  await page.evaluateOnNewDocument(() => {
    delete navigator.__proto__.webdriver;
  });
  //We stop images and stylesheet to save data
  await page.setRequestInterception(true);

  page.on('request', (request) => {
    if(['image', 'stylesheet', 'font'].includes(request.resourceType())) {
      request.abort();
    } else {
      request.continue();
    }
  })
const args = process.argv.slice(2)
const userLink = args[0]


  await page.goto(userLink); //change this to user url page
  let username = page.url().slice(23,).replace(/[-:.\/*<>|?]/g,"");

  //scroll down until no more videos
  await autoScroll(page);

  const urls = await page.evaluate(() => 
    Array.from(document.querySelectorAll('div.tiktok-1qb12g8-DivThreeColumnContainer > div > div > div > div > div > a'), element => element.href));

  var videoDes = await page.evaluate(() =>Array.from(document.querySelectorAll('div.tiktok-1qb12g8-DivThreeColumnContainer.eegew6e2 > div > div > div > a')).map((items) => items.innerText))
  
    for (var i = 0; i < videoDes.length; i++) {
      
      videoDes[i] = videoDes[i].replace(/[|&;$%@"{}<>.:'*/()+#!`,]/g, "").substring(0,255)}; //append #shorts for each video title
      videoDes.unshift(0)
      // let videoDescription = videoDes[videoDes.length + 1]
      console.log(videoDes);

      const fs = require('fs');

      fs.appendFile('names.txt', videoDes + '', function (err) {
        if (err) throw err;
        console.log('Descriptions Saved!');
      });
        console.log('now it downloading ' +urls.length+ ' video' ) 
//loop on snaptik for no watermark tiktok videos
      //becareful that can be alot of gigas if profile has a lot of videos
    for (var i=0;i<urls.length;i++) //you can limit number of videos by replace url.length by number
    {
      function getRandomNumber() {
        var random = Math.floor(Math.random() * (500 - 300 + 1)) + 300;
         return random;
       };
       function getHighNumber() {
        var random = Math.floor(Math.random() * (500 - 300 + 1)) + 1150;
         return random;
       };
    await page.waitForTimeout(getHighNumber());
    await page.goto('https://snaptik.app/');
    await page.waitForTimeout(getRandomNumber());
    await page.waitForSelector('input[name="url"]');
    await page.type('input[name="url"]' , (urls[i]) , {delay: 100}); //type result of links
 //   let link = (urls[i]).slice(-19)
    await page.waitForTimeout(getRandomNumber());
    // await page.keyboard.press('Enter');
    await page.click('#submiturl')
    await page.waitForTimeout(getHighNumber());
    await page.waitForXPath('//*[@id="download-block"]/div/a[1]');
    const featureArticle = (await page.$x('//*[@id="download-block"]/div/a[1]'))[0];
    // the same as:
    // const featureArticle = await page.$('#mp-tfa');

    const text = await page.evaluate(el => {
        // do what you want with featureArticle in page.evaluate
        return el.href;
    }, featureArticle);
    var noWaterMark = text
    const content = decodeURIComponent(noWaterMark);

    
    const https = require('https');
    const ds = require('fs');

    
     // link to file you want to download
     const path = './'+username+'/'; // location to save videos
     try {
       if (!ds.existsSync(path)) {
         ds.mkdirSync(path)
       }
     } catch (err) {
       console.error(err)
     }
   
    const request = https.get(content, function(response) {
        if (response.statusCode === 200) {
            var file = ds.createWriteStream(path+videoDes[i].slice(0)+'.mp4');
            response.pipe(file);
            console.log(file.path + ' Saved!')
          
            const fs = require('fs');

            fs.appendFile('names.txt',file.path +  "\r\n" , function (err) {
            if (err) throw err;
            console.log('Done');
            });
        }

        // request.setTimeout(60000, function() { // if after 60s file not downlaoded, we abort a request 
        //     request.destroy();
    // });
    });
    ;};

  
    browser.close();
  }

async function autoScroll(page){
  await page.evaluate(async () => {
      await new Promise((resolve, reject) => {
          var totalHeight = 0;
          var distance = 100;
          var timer = setInterval(() => {
              var scrollHeight = document.body.scrollHeight;
              window.scrollBy(0, distance);
              totalHeight += distance;

              if(totalHeight >= scrollHeight){
                  clearInterval(timer);
                  resolve();
              }
          }, 100);
      });
  });
}
`


usage : node filename profile url

**Comment by Karim-Arab** [comment]
@i6c  it's tricky because have to strip windows illegal chars from descriptions but here we go

replace 
`    for (var i=videoDes.length; i--;) {
      videoDes[i] = videoDes[i] + ' #shorts' + "\r\n" ;};`

with 

`for (var i = 0; i < videoDes.length; i++) {
      
      videoDes[i] = videoDes[i].replace(/[|&;$%@"{}<>.:'*/()+#!`,]/g, "").substring(0,255)}; //append #shorts for each video title
      videoDes.unshift(0)
      console.log(videoDes);` 


delete this 

` let link = (urls[i]).slice(-19)`


instead of this 

`(path+link+'.mp4')`

change to this

`(path+videoDes[i].slice(0)+'.mp4')`


now you can download it with description file name instead of unique identifier
